---
# tasks file for ansible-unbound
- include: check-docker.yml
  when: ansible_os_family == "Debian"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_unbound.yml
  when: config_unbound

- include: systemd-resolved.yml
  when: ansible_os_family == "Debian"
