---
- name: stop and disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no
  when: 'docker_interface_name | length > 0'
  changed_when: false

- name: delete existing resolv.conf
  ansible.builtin.file:
    path: '/etc/resolv.conf'
    state: absent
  when: 'docker_interface_name | length > 0'
  changed_when: false

- name: create resolv.conf for unbound
  copy:
    dest: '/etc/resolv.conf'
    content: |
      # Ansible managed
      nameserver {{ docker_interface_ip }}
  when: 'docker_interface_name | length > 0'
  changed_when: false

- name: restart unbound service
  ansible.builtin.service:
    name: unbound
    state: restarted

- name: restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted
