---
- name: Get docker interface name
  set_fact:
    docker_interface_name: '{{ item }}'
  loop: '{{ ansible_facts.interfaces }}'
  when: 'item is regex("^docker[0-9]")'

- name: Get docker interface ip
  set_fact:
    docker_interface_ip: '{{ hostvars[inventory_hostname]["ansible_" ~ docker_interface_name]["ipv4"]["address"] }}'
  when: 'docker_interface_name | length > 0'

- name: debug
  debug:
    msg: 'Interface {{ docker_interface_name }} found'
  when: 'docker_interface_name | length > 0'

- name: debug
  debug:
    msg: '{{ docker_interface_ip }}'
  when: 'docker_interface_ip | length > 0'

- name: stop and disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no
  when: 'docker_interface_name | length > 0'
  changed_when: false

- name: delete existing resolv.conf
  ansible.builtin.file:
    path: '/etc/resolv.conf'
    state: absent
  when: 'docker_interface_name | length > 0'
  changed_when: false

- name: create resolv.conf for unbound
  copy:
    dest: '/etc/resolv.conf'
    content: |
      # Ansible managed
      nameserver {{ docker_interface_ip }}
  when: 'docker_interface_name | length > 0'
  changed_when: false
